### PR TITLE
[WIP] add caching of results

### PR DESCRIPTION
**Pull request by Flow191**
This PR is a work-in-progress, please don't merge (yet).
It is adding the `conn` parameter to `get_classification()` to supply a local RSQLite database to cache results.

### CODE REVIEW

**Comment by sneumann** [comment]
Thanks Florian for the PR, two people in our group will give your branch a test-drive, and then we can remove the [WIP] tag. 
It would be great if @wilsontom could "First-time contributors need a maintainer to approve running workflows." , not sure how that works, though, but it avoids that random people do bitcoin mining with github workflows. Yours, Steffen

**Comment by wilsontom** [comment]
@Flow191 Thanks very much for the PR. I've changed the upstream branch to a new branch which doesn't contain the vignette; as there is a bug which is stopping the package from the passing the build checks. @sneumann if the `no-vignette` branch is used for any testing; and then the `cache` can be merged with `devel` and `master` once the vignette is compiling properly.

Thanks

Tom

**Comment by wilsontom** [comment]
@Flow191 I am in the process of submitting the update version of classyfireR to CRAN. Please could you add your details to Authors@R as a `ctb`, in the `devel` branch ?

Thanks

Tom

**Comment by Flow191** [comment]
Hey Tom, 

sorry for the late reply. Maybe you can add my person-details to the DESCRIPTION in the devel branch? I'm not sure the best way to do that.
That would be the line: 
`person("Florian", "Schmidt", ,"florianxschmidt@web.de", "ctb")`
Would be awesome!

Florian

**Comment by wilsontom** [comment]
Hi Florian,

That's great, now I've got the details I can add it to the DESCRIPTION.

Will get this off to CRAN today.

Thanks again for your help with the local caching !

Tom

**Comment by Flow191** [comment]
That sounds very good! I enjoyed the work with the local caching. 

Thank you for including the feature in the package.

Florian

**Pull request merged**
